# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "base"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  # config.vm.network :private_network, virtualbox__intnet: "vboxnet0", ip: "10.0.69.11"
  # config.vm.network :public_network

  config.ssh.forward_agent = true

  # config.vm.synced_folder "../data", "/vagrant_data"

  # config.vm.provider :virtualbox do |vb|
  #   vb.customize ["modifyvm", :id, "--memory", "2048"]
  #   vb.customize ["modifyvm", :id, "--cpus", "4"]   
  #   vb.customize ["modifyvm", :id, "--ioapic", "on"] 
  # end  
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../cookbooks"
    # chef.roles_path = "../my-recipes/roles"
    # chef.data_bags_path = "../my-recipes/data_bags"
    chef.add_recipe "apt"
    chef.add_recipe "rabbitmq::default"
    chef.add_recipe "rabbitmq::mgmt_console"
    chef.add_recipe "workflows::hyperflow-engine"
    chef.add_recipe "workflows::amqp-executor"
    chef.add_recipe "workflows::montage"
    # chef.add_role "hyperflow-executor"
  
    # You may also specify custom JSON attributes:
    chef.json = { 
        "apt" => {"compiletime" => true},
        "amqp_executor" => {
          "AMQP_URL" => "amqp://localhost",
          "STORAGE" => "local"
        }
      }
      
    chef.log_level = :debug
  end
end
